# Generated by Django 3.0.8 on 2020-07-31 05:04

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_MV', models.CharField(max_length=100, unique=True)),
                ('name1_MV', models.CharField(blank=True, max_length=100)),
                ('time_Post', models.DateTimeField(auto_now=True)),
                ('singer_MV', models.CharField(max_length=200)),
                ('intro_MV', models.CharField(max_length=500)),
                ('category_MV', models.CharField(choices=[('K-Pop', 'K-Pop'), ('V-Pop', 'V-Pop'), ('US-UK', 'US-UK')], max_length=10)),
                ('description_MV', ckeditor_uploader.fields.RichTextUploadingField()),
                ('img_MV', models.ImageField(upload_to='img_mv/')),
                ('link_Youtube', models.CharField(max_length=500, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
                ('view', models.IntegerField(default=0)),
                ('author_MV', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='mv_likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
