# Generated by Django 3.0.8 on 2020-07-31 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelmv',
            name='category_MV',
            field=models.CharField(choices=[('K-Pop', 'K-Pop'), ('US-UK', 'US-UK'), ('V-Pop', 'V-Pop')], max_length=10),
        ),
    ]
